auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: hanqi's blog
url: http://hanqi91.github.io
feed: /atom.xml
author_info: <a href="http://hanqi91.github.io/">hanqi</a>
